namespace: "tubby1981"
name: "system"
version: "1.0.0"
readme: "README.md"
authors:
  - "Tromp Wezelman"
license: "MIT"
tags:
  - linux
  - firewall
  - servers
  - foomuuri
dependencies: {}
repository: "https://github.com/tubby1981/ansible"
homepage: "https://github.com/tubby1981/ansible"
issues: "https://github.com/tubby1981/ansible/issues"
documentation: "https://github.com/tubby1981/ansible/blob/main/README.md"
