---
namespace: tubby1981
name: system
version: 1.0.5
readme: README.md
authors:
  - Tubby1981 <tubby1981@users.noreply.github.com>
description: >-
  Ansible collection for Linux system management featuring Foomuuri -
  a modern multizone bidirectional nftables firewall with advanced NAT,
  dynamic IP lists, and comprehensive security features. Includes roles
  for Apache2 webserver with Let's Encrypt SSL, MariaDB database server,
  PHP and phpMyAdmin support, Hetzner Cloud network automation with 
  PowerDNS Recursor for recursive DNS resolution, and a production-ready 
  mail server with Postfix, Dovecot, PostfixAdmin, SpamAssassin, ClamAV, 
  and OpenDKIM.
license: MIT
tags:
  - firewall
  - nftables
  - security
  - linux
  - debian
  - networking
  - infrastructure
  - apache2
  - letsencrypt
  - mariadb
  - hetzner
  - cloud
  - dns
  - mail
  - postfix
  - dovecot
  - spamassassin
  - monitoring
  - automation
  - devops
dependencies: {}
repository: https://github.com/tubby1981/ansible
documentation: https://github.com/tubby1981/ansible/blob/main/README.md
homepage: https://tubby1981.github.io/ansible/
issues: https://github.com/tubby1981/ansible/issues
build_ignore:
  - .gitignore
  - .git
  - .github
  - '*.tar.gz'
  - tests/output
  - host_vars
  - group_vars
  - inventory
