---
namespace: tubby1981
name: system
version: 1.0.0
readme: README.md
authors:
  - Tubby1981 <tubby1981@users.noreply.github.com>

description: >-
  Ansible collection for Linux system management featuring Foomuuri -
  a modern multizone bidirectional nftables firewall with advanced NAT,
  dynamic IP lists, and comprehensive security features. **Now also includes
  a comprehensive role for managing the Apache2 webserver.**

license: MIT

tags:
  - firewall
  - nftables
  - foomuuri
  - security
  - linux
  - debian
  - ubuntu
  - archlinux
  - system
  - networking
  - nat
  - infrastructure
  - hardening
  - multizone
  - netfilter
  - apache
  - apache2
  - httpd
  - webserver

dependencies: {}

repository: https://github.com/tubby1981/ansible
documentation: https://github.com/tubby1981/ansible/blob/main/README.md
homepage: https://github.com/tubby1981/ansible
issues: https://github.com/tubby1981/ansible/issues

build_ignore:
  - .gitignore
  - .git
  - .github
  - '*.tar.gz'
  - tests/output
  - host_vars
  - group_vars
  - inventory
