firewall: "foomuuri"

foomuuri_extra_zones:
  - name: "public"
    interfaces:
      - "eth0"

foomuuri_extra_macros:
  # Trusted SSH IPv4
  - name: "ssh-ipv4-clients"
    ips: ["213.233.192.3", "212.45.32.83", "212.45.32.70"]

  # Trusted SSH IPv6
  - name: "ssh-ipv6-clients"
    ips: ["2001:9e0:8600:a00:de15:c8ff:fe7f:e3a1/64", "2001:9e0:4:32::83", "2001:9e0:4:32::70"]

  # Maildiensten
  - name: "mail-services"
    protocols: 
      tcp: [143, 587, 993, 995, 9001]

  # NetBIOS blokkeren - TCP en UDP hebben verschillende poorten
  - name: "netbios"
    protocols: 
      tcp: [139, 445]
      udp: [137, 138]

foomuuri_extra_zone_policies:
  - from_zone: "public"
    to_zone: "localhost"
    description: "Allow incoming traffic"
    rules:
      - "ssh saddr ssh-ipv4-clients"
      - "ssh saddr ssh-ipv6-clients"
      - "http"
      - "https"
      - "mail-services"
      - "netbios drop"
      - "ping"
      - "drop log"
  - from_zone: "localhost"
    to_zone: "public"
    description: "Allow outgoing traffic"
    rules:
      - accept
